pipeline:
  - type: azdo
    files:
      - name: variable
        path: build/azDevOps/azure/air-infrastructure-data.json
    templates:
      - name: variable
        path: build/azDevOps/azure/air-infrastructure-data-template.json

setup:
  operations:
    - action: copy
