pipeline:
  - type: azdo
    files:
      - name: build
        path: build/azDevOps/azure/templates/air-infrastructure-data.yml
      - name: variable
        path: build/azDevOps/azure/air-infrastructure-data-vars.yml
    templates:
      - name: variable
        path: build/azDevOps/azure/air-infrastructure-data-vars-template.yml
  - type: azdo
    files:
      - name: variable
        path: build/azDevOps/azure/air-infrastructure-data.json
    templates:
      - name: variable
        path: build/azDevOps/azure/air-infrastructure-data-template.json

setup:
  operations:
    - action: copy
