# Import contexts and tasks for Taskctl
import:
  - ./build/taskctl/contexts.yaml
  - ./build/taskctl/tasks.yaml

watchers:
  lint:
    watch:
      - '*.yml'
      - '*.yaml'
    events: [create, write]
    task: lint:yaml

pipelines:
  setup:
    - task: debug:env
    - task: buildnumber
      depends_on:
        - debug:env

  lint:
    - task: lint:precommit
    - task: lint:yaml
      depends_on: lint:precommit
    - task: lint:terraform:format
      depends_on: lint:precommit
    - task: lint:terraform:validate
      depends_on: lint:precommit

  # Pipeline to ensure that the infrastructure is valid
  infrastructure:
    - task: infra:init
    - task: infra:plan
      depends_on: infra:init
    - task: infra:apply
      depends_on: infra:plan

  infrastructurePlan:
    - task: infra:init
    - task: infra:plan
      depends_on: infra:init
    - task: infra:apply
      depends_on: infra:plan

  databricks:
    - task: databricks:connect
    - task: databricks:createdir
      depends_on: databricks:connect
    - task: databricks:upload
      depends_on: databricks:createdir

  deworkloadTesting:
    - task: deworkload:Testing
