# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Sample YAML file to validate and export an ARM template into a build artifact
# Requires a package.json file located in the target repository

name: "$(Build.SourceBranchName)-init"

trigger:
- none

# pr:
#   - main

# trigger:
#   branches:
   
#     include:
#       - 'main'
#   paths:
#     include:
#       - data_quality/config/*
#       - data_quality/data-quality-config-pipeline.yml


variables:
  - template: ../de_build/job-pipeline-vars.yml
#  - template: de_build/adf/air-data-testing-vars.yml
  # - name: job  #update job name
  #   value: 'Generate_Ingest_Query'
  - name: self_repo_blob_config
    value: "$(self_repo_dir)/data_quality/config"
  - name: blob_config_destination
    value: config

pool:
  name: $(agentpool_name)

stages:
- stage: Release
  variables:
      - group: amido-stacks-infra-credentials-nonprod
      - name: version_number
        value: "$(version_major).$(version_minor).$(version_revision)"
  jobs:
      - job: CreateGitHubRelease
        pool:
          name: $(agentpool_name)
        steps:
          # Check out the repo so that it can be tagged
          - checkout: self
            persistCredentials: true

          - script: |
              lastTag=$(git describe --tags --abbrev=0)
              if [[ -z $lastTag ]]; then
                version_major=1
                version_minor=0
                version_revision=0
                echo "Last Tag: NOT Present"
              else
                IFS='.' read -ra versionParts <<< "${lastTag#v}"
                version_major="${versionParts[0]}"
                version_minor="${versionParts[1]}"
                lastversion_revision="${versionParts[2]}"
                version_revision=$((lastversion_revision + 1))
              fi
              newVersion="v${version_major}.${version_minor}.${version_revision}"
              echo "Last Tag: $lastTag"
              echo "New Version: $newVersion"
              echo "##vso[task.setvariable variable=newVersion]$version_major"
              echo "##vso[task.setvariable variable=newVersion]$version_minor"
              echo "##vso[task.setvariable variable=newVersion]$version_revision"
              echo "##vso[task.setvariable variable=newVersion]$newVersion"
            displayName: Determine New Version

          # # Create a new tag with the incremented version
          # - script: |
          #     git config user.name "BuildService"
          #     git config user.email "builder@${COMPANY}.com"
          #     git tag -a ${{ variables.newVersion }} -m "Release created by Azure DevOps"
          #     git push origin ${{ variables.newVersion }}
          #   displayName: Create New Tag

          #           # Create a GitHub release with these packages
          # - task: GitHubRelease@1
          #   displayName: Create GitHub Release
          #   inputs:
          #     gitHubConnection: $(github_release_service_connection)
          #     repositoryName: $(github_org)/$(self_repo)
          #     tag: ${{ variables.newVersion }}
          #     releaseNotesSource: 'inline'
          #     releaseNotesInline: "$(version_major).$(version_minor).$(version_revision)"
          #     tagSource: 'gitTag'
          #     changeLogCompareToRelease: 'lastFullRelease'
          #     changeLogType: 'commitBased'

