# Build and deploy pipeline for job Ingest_AzureSql_Example

name: "$(Build.SourceBranchName)-init"

pr:
  branches:
    include:
      - "main"
  paths:
    include:
      - de_workloads/ingest/Ingest_AzureSql_Example/*

trigger:
  branches:
    include:
      - "main"
  paths:
    include:
      - de_workloads/ingest/Ingest_AzureSql_Example/*

variables:
  - template: ../../../build/common-vars.yml
  - template: ../../../de_build/job-pipeline-vars.yml
  - template: ../../../build/version-data-vars.yml
  - name: job  # update job name
    value: "Ingest_AzureSql_Example"
  - name: jobtype  # update job type
    value: "ingest"
  - name: include_data_quality  # update data quality option
    value: "true"
  - name: self_repo_job_dir
    value: "$(self_repo_dir)/de_workloads/$(jobtype)/$(job)"
  - name: self_repo_adf_dir
    value: "$(self_repo_job_dir)/data_factory"
  - name: test_unit_src
    value: "de_workloads/$(jobtype)/$(job)/tests/unit/"
  - name: test_end_to_end_src
    value: "de_workloads/$(jobtype)/$(job)/tests/end_to_end/features/"
  - name: junit_src
    value: "de_workloads/$(jobtype)/$(job)/junit"
  - name: self_repo_sparkjob_dir
    value: "$(self_repo_job_dir)/spark_jobs"
  - name: self_repo_adf_src
    value: "de_workloads/$(jobtype)/$(job)/data_factory"
  - name: self_repo_blob_config
    value: "$(self_repo_job_dir)/config"
  - name: blob_config_destination
    value: "config/$(jobtype)/$(job)"
  - name: tf_state_key
    value: $(domain)_$(jobtype)_$(job)
  - name: dbfs_destination  # update job name
    value: 'dbfs:/FileStore/scripts/Ingest_AzureSql_Example_DQ'
  - name: self_repo_spark_src
    value: "de_workloads/$(jobtype)/$(job)/spark_jobs"

pool:
  name: $(agentpool_name)

stages:
  - stage: Build_Stage
    variables:
      - group: stacks-credentials-nonprod-kv
      - group: amido-stacks-de-pipeline-nonprod
    jobs:
      - job: Build_Job
        displayName: "Build_Job"
        steps:
          - task: Bash@3
            displayName: "Clean Workspace"
            inputs:
              targetType: "inline"
              script: |
                echo "Cleaning workspace..."
                sudo rm -rf $(Build.SourcesDirectory)/*
                sudo rm -rf $(Build.SourcesDirectory)/.pytest_cache/*
                sudo rm -f $(Build.SourcesDirectory)/.pytest_cache/.gitignore
          # Publish Config files
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(service_connection)
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              inlineScript: |
                az storage blob upload-batch `
                --source $(self_repo_blob_config) `
                --destination $(blob_config_destination) `
                --account-name $(blob_configStorage) `
                --overwrite
