# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Sample YAML file to validate and export an ARM template into a build artifact
# Requires a package.json file located in the target repository

trigger:
#- main #collaboration branch
- none


pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build_Stage
  variables:
      - group: amido-stacks-de-pipeline-nonprod
      - name: version_number
        value: "$(version_major).$(version_minor).$(version_revision)"
  jobs:
  - job: Build_Adf_Configfiles_Build
    displayName: 'ADF-CONFIGFILES-BUILD'

    steps:

    # Installs Node and the npm packages saved in your package.json file in the build

    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.Repository.LocalPath)/build' #replace with the package.json folder
        verbose: true
      displayName: 'Install npm package'

    # Validates all of the Data Factory resources in the repository. You'll get the same validation errors as when "Validate All" is selected.
    # Enter the appropriate subscription and name for the source factory. Either of the "Validate" or "Validate and Generate ARM temmplate" options are required to perform validation. Running both is unnecessary.

    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: '$(Build.Repository.LocalPath)/build' #replace with the package.json folder
        customCommand: 'run build validate $(Build.Repository.LocalPath)/data_factory /subscriptions/$(azure-subscription-id)/resourceGroups/amido-stacks-dev-euw-adfpoc/providers/Microsoft.DataFactory/factories/amido-stacks-dev-euw-adfdev'
      displayName: 'Validate'

    # Validate and then generate the ARM template into the destination folder, which is the same as selecting "Publish" from the UX.
    # The ARM template generated isn't published to the live version of the factory. Deployment should be done by using a CI/CD pipeline. 

    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: '$(Build.Repository.LocalPath)/build' #replace with the package.json folder
        customCommand: 'run build export $(Build.Repository.LocalPath)/data_factory /subscriptions/$(azure-subscription-id)/resourceGroups/amido-stacks-dev-euw-adfpoc/providers/Microsoft.DataFactory/factories/amido-stacks-dev-euw-adfdev "ArmTemplate"'
    #For using preview that allows you to only stop/ start triggers that are modified, please comment out the above line and uncomment the below line. Make sure the package.json contains the build-preview command. 
    #customCommand: 'run build-preview export $(Build.Repository.LocalPath) /subscriptions/222f1459-6ebd-4896-82ab-652d5f6883cf/resourceGroups/GartnerMQ2021/providers/Microsoft.DataFactory/factories/Dev-GartnerMQ2021-DataFactory "ArmTemplate"'
      displayName: 'Validate and Generate ARM template'

    # Publish the artifact to be used as a source for a release pipeline.

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact: ArmTemplates'
      inputs:
        targetPath: '$(Build.Repository.LocalPath)/build/ArmTemplate' #replace with the package.json folder
        artifact: 'ArmTemplates'
        publishLocation: 'pipeline'

    - task: CopyFiles@2
      displayName: 'Copy Config Files '
      inputs:
        SourceFolder: config
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: ConfigFiles'
      inputs:
        ArtifactName: ConfigFiles

#############################################################
# Deploy to non Prod
#############################################################
- stage: Deploy_UAT_Stage
  variables:
      - group: amido-stacks-de-pipeline-nonprod
      - name: version_number
        value: "$(version_major).$(version_minor).$(version_revision)"
  dependsOn: Build_Stage
  jobs:
  - deployment: Deploy_UAT
    displayName: 'Deploy To UAT'
    environment: ADFUAT
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:  
          steps:


           - task: DownloadPipelineArtifact@2
             displayName: Download Build Artifacts
             inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
           - script: dir
             displayName: List ConfigFiles Artifact in Workspace
             workingDirectory: '$(System.DefaultWorkingDirectory)/ConfigFiles'
           - script: dir
             displayName: List ArmTemplates Artifact in Workspace
             workingDirectory: '$(System.DefaultWorkingDirectory)/ArmTemplates'

    # Publish Config files
           - task: AzureCLI@2
             inputs:
               azureSubscription: 'amido.stacks'
               scriptType: 'pscore'
               scriptLocation: 'inlineScript'
               inlineScript: 'az storage blob upload-batch --source $(System.DefaultWorkingDirectory)/ConfigFiles --destination config --account-name uatsaforadfpoc --overwrite'

    # Publish ADF
           - task: AzurePowerShell@5
             displayName: 'Stop ADF triggers'
             inputs:
              azureSubscription: 'amido.stacks'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)/ArmTemplates/PrePostDeploymentScript.ps1'
              ScriptArguments:  -armTemplate "$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json"
                              -ResourceGroupName "amido-stacks-dev-euw-adfpoc"
                              -DataFactoryName "amido-stacks-uat-euw-adfuat"
                              -predeployment $true
                              -deleteDeployment $false
              azurePowerShellVersion: 'LatestVersion'

           - task: AzureResourceManagerTemplateDeployment@3
             displayName: 'ARM Template deployment: Resource Group scope'
             inputs:
                azureResourceManagerConnection: 'amido.stacks'
                subscriptionId: '$(azure-subscription-id)'
                resourceGroupName: 'amido-stacks-dev-euw-adfpoc'
                location: 'West Europe'
                csmFile: '$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json'
                csmParametersFile: '$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateParametersForFactory.json'
                overrideParameters: -factoryName "amido-stacks-uat-euw-adfuat" 
                                    -AzureBlobStorage_properties_typeProperties_connectionString_secretName "SA" 
                                    -AzureKeyVault_properties_typeProperties_baseUrl "https://uatkvforadfpoc.vault.azure.net/"
                deploymentMode: 'Incremental'

           - task: AzurePowerShell@5
             displayName: 'Clean resources and start ADF triggers'
             inputs:
              azureSubscription: 'amido.stacks'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)/ArmTemplates/PrePostDeploymentScript.ps1'
              ScriptArguments:  -armTemplate "$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json"
                              -ResourceGroupName "amido-stacks-dev-euw-adfpoc"
                              -DataFactoryName "amido-stacks-uat-euw-adfuat"
                              -predeployment $false
                              -deleteDeployment $True
              azurePowerShellVersion: 'LatestVersion'


#############################################################
# Deploy to non Prod
#############################################################
- stage: Deploy_Prod_Stage
  variables:
      - group: amido-stacks-de-pipeline-prod
      - name: version_number
        value: "$(version_major).$(version_minor).$(version_revision)"
  dependsOn: Build_Stage
  jobs:
  - deployment: Deploy_UAT
    displayName: 'Deploy To UAT'
    environment: ADFUAT
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:  
          steps:


           - task: DownloadPipelineArtifact@2
             displayName: Download Build Artifacts
             inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
           - script: dir
             displayName: List ConfigFiles Artifact in Workspace
             workingDirectory: '$(System.DefaultWorkingDirectory)/ConfigFiles'
           - script: dir
             displayName: List ArmTemplates Artifact in Workspace
             workingDirectory: '$(System.DefaultWorkingDirectory)/ArmTemplates'

    # Publish Config files
           - task: AzureCLI@2
             inputs:
               azureSubscription: 'amido.stacks'
               scriptType: 'pscore'
               scriptLocation: 'inlineScript'
               inlineScript: 'az storage blob upload-batch --source $(System.DefaultWorkingDirectory)/ConfigFiles --destination config --account-name uatsaforadfpoc --overwrite'

    # Publish ADF
           - task: AzurePowerShell@5
             displayName: 'Stop ADF triggers'
             inputs:
              azureSubscription: 'amido.stacks'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)/ArmTemplates/PrePostDeploymentScript.ps1'
              ScriptArguments:  -armTemplate "$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json"
                              -ResourceGroupName "amido-stacks-dev-euw-adfpoc"
                              -DataFactoryName "amido-stacks-uat-euw-adfuat"
                              -predeployment $true
                              -deleteDeployment $false
              azurePowerShellVersion: 'LatestVersion'

           - task: AzureResourceManagerTemplateDeployment@3
             displayName: 'ARM Template deployment: Resource Group scope'
             inputs:
                azureResourceManagerConnection: 'amido.stacks'
                subscriptionId: '$(azure-subscription-id)'
                resourceGroupName: 'amido-stacks-dev-euw-adfpoc'
                location: 'West Europe'
                csmFile: '$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json'
                csmParametersFile: '$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateParametersForFactory.json'
                overrideParameters: -factoryName "amido-stacks-uat-euw-adfuat" 
                                    -AzureBlobStorage_properties_typeProperties_connectionString_secretName "SA" 
                                    -AzureKeyVault_properties_typeProperties_baseUrl "https://uatkvforadfpoc.vault.azure.net/"
                deploymentMode: 'Incremental'

           - task: AzurePowerShell@5
             displayName: 'Clean resources and start ADF triggers'
             inputs:
              azureSubscription: 'amido.stacks'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)/ArmTemplates/PrePostDeploymentScript.ps1'
              ScriptArguments:  -armTemplate "$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json"
                              -ResourceGroupName "amido-stacks-dev-euw-adfpoc"
                              -DataFactoryName "amido-stacks-uat-euw-adfuat"
                              -predeployment $false
                              -deleteDeployment $True
              azurePowerShellVersion: 'LatestVersion'
