# Build and deploy pipeline for job

name: "$(Build.SourceBranchName)-init"

parameters:
  - name: force_deploy
    displayName: Force deploy regardless of branch
    type: boolean
    default: false
  - name: deploy
    displayName: Deploy Environment
    type: boolean
    default: true
  - name: destroy
    displayName: Destroy Environment
    type: boolean
    default: false
  - name: stages
    type: object
    default:
      - stage: NonProd
        dependsOn: Build
        condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
        environment_shortname: nonprod
      - stage: Prod
        dependsOn: Build
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        environment_shortname: prod
  - name: debug
    displayName: Turn on debug for the Independent Runner
    type: boolean
    default: false

pr:
  branches:
    include:
      - "main"
  paths:
    include:
      - de_workloads/processing/silver_movies_example/*

trigger:
  branches:
    include:
      - "main"
  paths:
    include:
      - de_workloads/processing/silver_movies_example/*

variables:
  - template: ../../../build/common-vars.yml
  - template: ../../../de_build/job-pipeline-vars.yml
  - template: ../../../build/version-data-vars.yml
  - name: pipeline_name
    value: "silver_movies_example"
  - name: workload_type
    value: "processing"
  - name: self_repo_pipeline_dir
    value: "$(self_repo_dir)/de_workloads/$(workload_type)/$(pipeline_name)"
  - name: self_repo_adf_dir
    value: "$(self_repo_pipeline_dir)/data_factory"
  - name: test_unit_src
    value: "de_workloads/$(workload_type)/$(pipeline_name)/tests/unit/"
  - name: test_end_to_end_src
    value: "de_workloads/$(workload_type)/$(pipeline_name)/tests/end_to_end/features/"
  - name: junit_src
    value: "de_workloads/$(workload_type)/$(pipeline_name)/junit"
  - name: self_repo_sparkjob_dir
    value: "$(self_repo_pipeline_dir)/spark_jobs"
  - name: self_repo_adf_src
    value: "de_workloads/$(workload_type)/$(pipeline_name)/data_factory"
  - name: self_repo_spark_src
    value: "de_workloads/$(workload_type)/$(pipeline_name)/spark_jobs"
  - name: tf_state_key
    value: $(domain)_$(workload_type)_$(pipeline_name)
  - name: dbfs_destination
    value: "dbfs:/FileStore/scripts/$(pipeline_name)"

pool:
  name: $(agentpool_name)

stages:
  - stage: Build
    variables:
      - group: ensono-sp-creds
    jobs:
      - job: Build_Job
        displayName: "Build_Job"
        steps:
          - task: Bash@3
            displayName: "Clean Workspace"
            inputs:
              targetType: "inline"
              script: |
                echo "Cleaning workspace..."
                sudo rm -rf $(Build.SourcesDirectory)/*
                sudo rm -rf $(Build.SourcesDirectory)/.pytest_cache/*
                sudo rm -f $(Build.SourcesDirectory)/.pytest_cache/.gitignore
          - template: ../../../build/azDevOps/templates/air-infrastructure-data-setup.yml
            parameters:
              TaskctlVersion: ${{ variables.TaskctlVersion }}
          - script: |
              lastTag=$(git tag --sort=-creatordate | head -n 1)
              if [[ -z $lastTag ]]; then
                major=$(version_major)
                minor=$(version_minor)
                revision=$(version_revision)
                echo "Last Tag: NOT Present"
              else
                IFS='.' read -ra versionParts <<< "${lastTag#v}"
                major="${versionParts[0]}"
                minor="${versionParts[1]}"
                lastrevision="${versionParts[2]}"
                revision=$((lastrevision + 1))
                echo "Last Tag: $lastTag"
              fi
              newVersion="${major}.${minor}.${revision}"
              echo "New Version: $newVersion"
              echo "##vso[task.setvariable variable=major]$major"
              echo "##vso[task.setvariable variable=minor]$minor"
              echo "##vso[task.setvariable variable=revision]$revision"
              echo "##vso[task.setvariable variable=newVersion]$newVersion"
            displayName: Determine New Version
          - task: Bash@3
            displayName: "TaskCTL: Setup"
            inputs:
              targetType: inline
              script: taskctl setup
            env:
              DOCKER_IMAGE_TAG: $(newVersion)
          - task: Bash@3
            displayName: "TaskCTL: Lint"
            inputs:
              targetType: inline
              script: taskctl lint
            env:
              # Dotnet Build
              CLOUD_PLATFORM: "$(cloud_platform)"
              TF_FILE_LOCATION: /app/$(self_repo_adf_src)

  - ${{ each stage in parameters.stages }}:
      - stage: ${{ stage.stage }}
        condition: and(succeeded(), or(${{ stage.condition }}, ${{ parameters.force_deploy }}))
        dependsOn: ${{ stage.dependsOn }}
        variables:
          - group: ensono-sp-creds
          - group: ensono-data-${{ stage.environment_shortname }}

        jobs:
          - deployment: Deploy_${{ stage.stage }}
            environment: ${{ variables.domain }}-${{ stage.environment_shortname }}
            pool:
              name: $(agentpool_name)

            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: Bash@3
                      displayName: "Clean Workspace"
                      inputs:
                        targetType: "inline"
                        script: |
                          echo "Cleaning workspace..."
                          sudo rm -rf $(Build.SourcesDirectory)/*
                          sudo rm -rf $(Build.SourcesDirectory)/.pytest_cache/*
                          sudo rm -f $(Build.SourcesDirectory)/.pytest_cache/.gitignore

                    - template: ../../../build/azDevOps/templates/air-infrastructure-data-setup.yml
                      parameters:
                        TaskctlVersion: ${{ variables.TaskctlVersion }}

                    - task: AzureKeyVault@2
                      inputs:
                        azureSubscription: $(service_connection)
                        KeyVaultName: $(keyvault_name)
                        SecretsFilter: "*"
                        RunAsPreJob: false
                      displayName: "Get secrets from the keyvault"

                    - task: Bash@3
                      displayName: "TaskCTL: Databricks"
                      inputs:
                        targetType: inline
                        script: taskctl databricks
                      env:
                        # Dotnet Build
                        DATABRICKS_HOST: "$(databricks-host)"
                        DATABRICKS_TOKEN: "$(databricks-token)"
                        DATABRICKS_DBFS_LOCATION: "$(dbfs_destination)"
                        DATABRICKS_SOURCE_LOCATION: "./$(self_repo_spark_src)/"

                    # Publish ADF
                    - task: Bash@3
                      displayName: "TaskCTL: infrastructure"
                      inputs:
                        targetType: inline
                        script: taskctl -d infrastructure
                      env:
                        # Dotnet Build
                        CLOUD_PLATFORM: "$(cloud_platform)"
                        TF_FILE_LOCATION: "/app/$(self_repo_adf_src)"
                        ENV_NAME: ${{ stage.environment_shortname }}

                        TF_BACKEND_INIT: "key=$(tf_state_key),storage_account_name=$(tf_state_storage),resource_group_name=$(tf_state_rg),container_name=$(tf_state_container)"
                        TF_VAR_data_factory_resource_group_name: $(resource_group)
                        TF_VAR_data_factory: $(datafactoryname)

          #   # Start Testing
          - deployment: Test_${{ stage.stage }}
            dependsOn: Deploy_${{ stage.stage }}
            environment: ${{ variables.domain }}-${{ stage.stage }}

            pool:
              name: $(agentpool_name)
            strategy:
              runOnce:
                deploy:
                  steps:
                    - template: ../../../de_build/de-workload-testing.yml
                      parameters:
                        pythonVersion: $(pythonVersion)
                        githubToken: $(github_token)
                        workingDirectory: "./"
                        unitTestLocation: "./$(test_unit_src)"
                        e2eTestLocation: "./$(test_end_to_end_src)"
                        azureSubscriptionId: $(ARM_SUBSCRIPTION_ID)
                        azureResourceGroupName: $(resource_group)
                        azureDataFactoryName: $(datafactoryname)
                        azureRegionName: $(region)
                        azureStorageAccountName: $(blob_adls_storage)
                        azureClientId: $(ARM_CLIENT_ID)
                        azureClientSecret: $(ARM_CLIENT_SECRET)
                        azureTenantId: $(ARM_TENANT_ID)

  - stage: Release
    dependsOn:
      - Build
      - Prod
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['create_release'], 'true'))
    jobs:
      - job: CreateGitHubRelease
        pool:
          name: $(agentpool_name)
        steps:
          - task: Bash@3
            displayName: "Clean Workspace"
            inputs:
              targetType: "inline"
              script: |
                echo "Cleaning workspace..."
                sudo rm -rf $(Build.SourcesDirectory)/*
                sudo rm -rf $(Build.SourcesDirectory)/.pytest_cache/*
                sudo rm -f $(Build.SourcesDirectory)/.pytest_cache/.gitignore

          # Check out the repo so that it can be tagged
          - checkout: self
            persistCredentials: true

          - script: |
              lastTag=$(git tag --sort=-creatordate | head -n 1)
              if [[ -z $lastTag ]]; then
                major=$(version_major)
                minor=$(version_minor)
                revision=$(version_revision)
                echo "Last Tag: NOT Present"
              else
                IFS='.' read -ra versionParts <<< "${lastTag#v}"
                major="${versionParts[0]}"
                minor="${versionParts[1]}"
                lastrevision="${versionParts[2]}"
                revision=$((lastrevision + 1))
                echo "Last Tag: $lastTag"
              fi
              newVersion="${major}.${minor}.${revision}"
              echo "New Version: $newVersion"
              echo "##vso[task.setvariable variable=major]$major"
              echo "##vso[task.setvariable variable=minor]$minor"
              echo "##vso[task.setvariable variable=revision]$revision"
              echo "##vso[task.setvariable variable=newVersion]$newVersion"
            displayName: Determine New Version

          - task: Bash@3
            displayName: Tag Code
            inputs:
              targetType: "inline"
              script: |
                commit=$(Build.SourceVersion)
                tag=$(git tag --contains $commit)
                if [ -z "$tag" ]; then
                  echo "Tag does not exist for the commit"
                  git config user.name "BuildService"
                  git config user.email "builder@${COMPANY}.com"
                  echo "Creating tag v${newVersion}..."
                  git tag -a "v${newVersion}" -m "Release created by Azure DevOps"
                  git push origin "v${newVersion}"
                  echo "##vso[task.setvariable variable=ShouldCreateRelease]True"
                else
                  echo "Tag '$tag' already exists for the commit.Skipping tag creation"
                  echo "##vso[task.setvariable variable=ShouldCreateRelease]false"
                fi
            env:
              COMPANY: $(company)
              newVersion: $(newVersion)

          # #           # Create a GitHub release with these packages
          - task: GitHubRelease@1
            displayName: Create GitHub Release
            inputs:
              gitHubConnection: $(github_release_service_connection)
              repositoryName: "$(Build.Repository.Name)"
              tag: v${newVersion}
              releaseNotesSource: "inline"
              releaseNotesInline: "$(major).$(minor).$(revision)"
              tagSource: "gitTag"
              changeLogCompareToRelease: "lastFullRelease"
              changeLogType: "commitBased"
            condition: eq(variables['ShouldCreateRelease'], 'true')
