name: "$(Build.SourceBranchName)-init"

pr:
  branches:
    include:
      - "main"
  paths:
    include:
      - datastacks/*
      - datastacks/datastacks-pipeline.yml
trigger:
  branches:
    include:
      - "main"
  paths:
    include:
      - datastacks/*
      - datastacks/datastacks-pipeline.yml
variables:
  - template: ../de_build/job-pipeline-vars.yml
  - template: ../de_build/air-data-testing-vars.yml
  - template: ../build/version-data-vars.yml
  - name: pythonVersion
    value: "3.10.10"

pool:
  name: $(agentpool_name)
stages:
  - stage: Build_Stage
    variables:
      - group: amido-stacks-de-pipeline-nonprod

    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(pythonVersion)
              githubToken: $(github_token)
              addToPath: true
            displayName: Set Python Version
          - bash: |
              pip install pylint pylint-exit pytest-cov poetry
            displayName: Install Pipeline Tools
          - bash: |
              poetry install
            displayName: Install Dependencies
            workingDirectory: $(self_repo_dir)
          - bash: |
              poetry run pytest -rf -v datastacks/tests/unit
            displayName: "Run Unit Tests"
            workingDirectory: "$(self_repo_dir)"
