# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Sample YAML file to validate and export an ARM template into a build artifact
# Requires a package.json file located in the target repository

name: "$(Build.SourceBranchName)-init"


pr:
  branches:
    include:
    - 'main'
  paths:
    include:
      - ingest/jobs/Generate_Ingest_Query/adfpipeline/*
      - ingest/jobs/Generate_Ingest_Query/tests/*
      - ingest/jobs/Generate_Ingest_Query/generate-ingest-query.yml

trigger:
  branches:
   
    include:
      - 'main'
  paths:
    include:
      - ingest/jobs/Generate_Ingest_Query/adfpipeline/*
      - ingest/jobs/Generate_Ingest_Query/tests/*
      - ingest/jobs/Generate_Ingest_Query/generate-ingest-query.yml





variables:
  - template: ../../../de_build/job-pipeline-vars.yml
  - template: ../../../de_build/air-data-testing-vars.yml
  - template: ../../../build/version-data-vars.yml
  - name: job  #update job name
    value: 'Generate_Ingest_Query'
  - name: self_repo_adf_dir
    value: "$(self_repo_dir)/ingest/jobs/$(job)/adfpipeline"
  - name: test_unit_path
    value: '$(self_repo_dir)/ingest/jobs/$(job)/tests/unit/'
  - name: test_end_to_end_path
    value: '$(self_repo_dir)/ingest/jobs/$(job)/tests/end_to_end/features/'
  - name: junit_path
    value: '$(self_repo_dir)/ingest/jobs/$(job)/junit/'
  - name: self_repo_adf_src  #update job name
    value: "$(jobtype)/jobs/$(job)/adfpipeline"
  - name: jobtype  #update job name
    value: 'ingest'

pool:
  name: $(agentpool_name)


stages:
- stage: Build_Stage
  variables:
      - group: amido-stacks-de-pipeline-nonprod
      - name: version_number
        value: "$(version_major).$(version_minor).$(version_revision)"
  jobs:
   - template: ../../../de_build/build-ingest-job.yml
     parameters:
      self_repo_dir: '$(self_repo_dir)'
      self_repo_adf_dir: '$(self_repo_adf_dir)'

#############################################################
# Deploy to non Prod
#############################################################
- stage: Deploy_NonPROD_Stage
  variables:
      - group: amido-stacks-de-pipeline-nonprod
      - group: amido-stacks-infra-credentials-nonprod
      - group: stacks-credentials-nonprod-kv
      - name: version_number
        value: "$(version_major).$(version_minor).$(version_revision)"
  dependsOn: Build_Stage
  jobs:
  - deployment: Deploy_NonPROD
    displayName: 'Deploy To NonPROD'
    environment: ${{ variables.domain }}-nonprod
    pool:
      name: $(agentpool_name)

    strategy:
      runOnce:
        deploy:  
          steps: 
           - task: DownloadPipelineArtifact@2
             displayName: Download Build Artifacts
             inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'

           - script: dir
             displayName: List ArmTemplates Artifact in Workspace
             workingDirectory: '$(System.DefaultWorkingDirectory)/ArmTemplates'
            
          #  - task: AzureCLI@2
          #    inputs:
          #      azureSubscription: 'amido.stacks (719637e5-aedd-4fb1-b231-5101b45f8bb5)'
          #      scriptType: 'pscore'
          #      scriptLocation: 'inlineScript'
          #      inlineScript: 'az deployment group what-if `
          #                     --resource-group $(resource_group) `
          #                     --template-file $(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json `
          #                     --parameters $(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateParametersForFactory.json `
          #                     --parameters factoryName=amido-stacks-dev-euw-de  `
          #                     --exclude-change-types Ignore'        

    # Publish ADF
           - task: AzurePowerShell@5
             displayName: 'Stop ADF triggers'
             inputs:
              azureSubscription: 'amido.stacks (719637e5-aedd-4fb1-b231-5101b45f8bb5)'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)/ArmTemplates/PrePostDeploymentScriptLatest.ps1'
              ScriptArguments:  -armTemplate "$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json"
                              -ResourceGroupName $(resource_group)
                              -DataFactoryName $(datafactoryname)
                              -predeployment $true
                              -deleteDeployment $false
              azurePowerShellVersion: 'LatestVersion'
           - template: ../../../build/azDevOps/templates/air-infrastructure-data-setup.yml
             parameters:
              TaskctlVersion: ${{ variables.TaskctlVersion }}

           - task: Bash@3
             displayName: "TaskCTL: Setup"
             inputs:
              targetType: inline
              script: taskctl setup
             env:
              DOCKER_IMAGE_TAG: $(version_number)   
           - task: Bash@3
             displayName: "TaskCTL: Lint"
             inputs:
               targetType: inline
               script: taskctl lint
             env:
              # Dotnet Build
              CLOUD_PROVIDER: "$(cloud_provider)"
              ARM_TENANT_ID: "$(azure-tenant-id)"
              ARM_SUBSCRIPTION_ID: "$(azure-subscription-id)"
              ARM_CLIENT_ID: "$(azure-client-id)"
              ARM_CLIENT_SECRET: "$(azure-client-secret)"
              TF_FILE_LOCATION: "./$(self_repo_adf_src)/"
           - task: Bash@3
             displayName: "TaskCTL: infrastructure"
             inputs:
              targetType: inline
              script: taskctl infrastructure
             env:
              # Dotnet Build
              CLOUD_PROVIDER: "$(cloud_provider)"
              ARM_TENANT_ID: "$(azure-tenant-id)"
              ARM_SUBSCRIPTION_ID: "$(azure-subscription-id)"
              ARM_CLIENT_ID: "$(azure-client-id)"
              ARM_CLIENT_SECRET: "$(azure-client-secret)"
              TF_FILE_LOCATION: "./$(self_repo_adf_src)/"
              ENV_NAME: $(Environment.ShortName)
                    # Azure Authentication
                    # Terraform Backend Configuration
              TF_STATE_CONTAINER: $(tf_state_container)
              TF_STATE_KEY: $(tf_state_key_dev)
              TF_STATE_RG: $(tf_state_rg)
              TF_STATE_STORAGE: $(tf_state_storage)
              TF_BACKEND_ARGS: "key=$(tf_state_key_dev),storage_account_name=$(TF_STATE_STORAGE),resource_group_name=$(TF_STATE_RG),container_name=$(TF_STATE_CONTAINER),subscription_id=$(azure-subscription-id),tenant_id=$(azure-tenant-id),client_id=$(azure-client-id),client_secret= $(azure-client-secret)"
                    # Deployment Specific Configuration
           - task: AzurePowerShell@5
             displayName: 'Clean resources and start ADF triggers'
             inputs:
              azureSubscription: 'amido.stacks (719637e5-aedd-4fb1-b231-5101b45f8bb5)'
              ScriptType: 'FilePath'
              ScriptPath: '$(self_repo_dir)/de_build/adf/PrePostDeploymentScriptLatest.ps1'
              ScriptArguments:  -armTemplate "$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json"
                              -ResourceGroupName $(resource_group)
                              -DataFactoryName $(datafactoryname)
                              -predeployment $false
                              -deleteDeployment $false
              azurePowerShellVersion: 'LatestVersion'

    # Start Testing 
  - deployment: Test_NonPROD
    displayName: 'Testing  NonPROD'
    environment: ${{ variables.domain }}-nonprod
    dependsOn: Deploy_NonPROD
    pool:
      name: $(agentpool_name)
    strategy:
      runOnce:
        deploy:  
          steps:
           - checkout: self
           - task: AzureCLI@2
             inputs:
               azureSubscription: 'amido.stacks (719637e5-aedd-4fb1-b231-5101b45f8bb5)'
               ScriptType: 'bash'
               scriptLocation: 'inlineScript'
               inlineScript: az account show 
           
           - task: UsePythonVersion@0
             inputs:
                versionSpec: '$(pythonVersion)'
                githubToken: '$(github_token)'
                addToPath: true

             displayName: Set Python Version

           - bash: |
              pip install pytest pylint pylint-exit pytest-azurepipelines pytest-cov poetry
             displayName: 'Install Pipeline Tools'
           - bash: |
              poetry install 
             displayName: 'Running poetry install'
             workingDirectory:  '$(self_repo_dir)'
           - bash: |
               python -m pytest $(test_unit_path)
             displayName: 'Running py test'
             workingDirectory:  '$(self_repo_dir)'

           - bash: |
               poetry run behave $(test_end_to_end_path)  --junit --junit-directory $(junit_path)
             displayName: 'Running e2e Test'
             workingDirectory:  '$(self_repo_dir)'
             env:
                  AZURE_SUBSCRIPTION_ID: $(azure_subscription_id)
                  AZURE_RESOURCE_GROUP_NAME: $(resource_group)
                  AZURE_DATA_FACTORY_NAME: $(datafactoryname)
                  AZURE_REGION_NAME: $(region)
                  AZURE_STORAGE_ACCOUNT_NAME: $(blob_adls_storage)
                  AZURE_CLIENT_ID: $(azure-client-id)
                  AZURE_CLIENT_SECRET: $(azure-client-secret)
                  AZURE_TENANT_ID: $(azure-tenant-id)   

           - task: PublishTestResults@2
             displayName: 'Publish Test Results'
             inputs:
                testResultsFiles: '**/*.xml'
                searchFolder: $(junit_path)
             condition: succeededOrFailed()
  

#############################################################
# Deploy to Prod
#############################################################
- stage: Deploy_Prod_Stage
  dependsOn: 
    - Build_Stage
    - Deploy_NonPROD_Stage
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
      - group: amido-stacks-de-pipeline-prod
      - name: version_number
        value: "$(version_major).$(version_minor).$(version_revision)"
  jobs:
  - deployment: Deploy_PRDO
    displayName: 'Deploy To PROD'
    environment: ${{ variables.domain }}-prod
    pool:
      name: $(agentpool_name)

    strategy:
      runOnce:
        deploy:  
          steps:


           - task: DownloadPipelineArtifact@2
             displayName: Download Build Artifacts
             inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'

           - script: dir
             displayName: List ArmTemplates Artifact in Workspace
             workingDirectory: '$(System.DefaultWorkingDirectory)/ArmTemplates'

    # Publish ADF
           - task: AzurePowerShell@5
             displayName: 'Stop ADF triggers'
             inputs:
              azureSubscription: 'amido.stacks (719637e5-aedd-4fb1-b231-5101b45f8bb5)'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)/ArmTemplates/PrePostDeploymentScriptLatest.ps1'
              ScriptArguments:  -armTemplate "$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json"
                              -ResourceGroupName $(resource_group)
                              -DataFactoryName $(datafactoryname)
                              -predeployment $true
                              -deleteDeployment $false
              azurePowerShellVersion: 'LatestVersion'

           - task: AzureResourceManagerTemplateDeployment@3
             displayName: 'ARM Template deployment: Resource Group scope'
             inputs:
                azureResourceManagerConnection: 'amido.stacks (719637e5-aedd-4fb1-b231-5101b45f8bb5)'
                subscriptionId: '$(azure_subscription_id)'
                resourceGroupName: $(resource_group)
                location: $(region)
                csmFile: '$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json'
                csmParametersFile: '$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateParametersForFactory.json'
                overrideParameters: -factoryName $(datafactoryname)
                deploymentMode: 'Incremental'

           - task: AzurePowerShell@5
             displayName: 'Clean resources and start ADF triggers'
             inputs:
              azureSubscription: 'amido.stacks (719637e5-aedd-4fb1-b231-5101b45f8bb5)'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)/ArmTemplates/PrePostDeploymentScriptLatest.ps1'
              ScriptArguments:  -armTemplate "$(System.DefaultWorkingDirectory)/ArmTemplates/ARMTemplateForFactory.json"
                              -ResourceGroupName $(resource_group)
                              -DataFactoryName $(datafactoryname)
                              -predeployment $false
                              -deleteDeployment $false
              azurePowerShellVersion: 'LatestVersion'
 
- stage: Release
  dependsOn:
      - Build_Stage
      - Deploy_Prod_Stage
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['create_release'], 'true'))
  variables:
      - group: amido-stacks-infra-credentials-nonprod
      # - name: version_number
      #   value: "$(version_major).$(version_minor).$(version_revision)"
  jobs:
      - job: CreateGitHubRelease
        pool:
          name: $(agentpool_name)
        steps:
          # Check out the repo so that it can be tagged
          - checkout: self
            persistCredentials: true

          - script: |
              lastTag=$(git tag --sort=-creatordate | head -n 1)
              if [[ -z $lastTag ]]; then
                major=$(version_major)
                minor=$(version_minor)
                revision=$(version_revision)
                echo "Last Tag: NOT Present"
              else
                IFS='.' read -ra versionParts <<< "${lastTag#v}"
                major="${versionParts[0]}"
                minor="${versionParts[1]}"
                lastrevision="${versionParts[2]}"
                revision=$((lastrevision + 1))
                echo "Last Tag: $lastTag"
              fi
              newVersion="${major}.${minor}.${revision}"
              echo "New Version: $newVersion"
              echo "##vso[task.setvariable variable=major]$major"
              echo "##vso[task.setvariable variable=minor]$minor"
              echo "##vso[task.setvariable variable=revision]$revision"
              echo "##vso[task.setvariable variable=newVersion]$newVersion"
            displayName: Determine New Version

          # Create a new tag with the incremented version
          # - script: |
          #     git config user.name "BuildService"
          #     git config user.email "builder@${COMPANY}.com"
          #     git tag -a ${newVersion} -m "Release created by Azure DevOps"
          #     git push origin ${newVersion}
          #   displayName: Create New Tag

          - task: Bash@3
            displayName: Tag Code
            inputs:
              targetType: "inline"
              script: |
                git config user.name "BuildService"
                git config user.email "builder@${COMPANY}.com"
                git tag -a v${newVersion} -m "Release created by Azure DevOps"
                git push origin v${newVersion}
            env:
              COMPANY: $(company)
              newVersion: $(newVersion)         

                    # Create a GitHub release with these packages
          - task: GitHubRelease@1
            displayName: Create GitHub Release
            inputs:
              gitHubConnection: $(github_release_service_connection)
              repositoryName: $(github_org)/$(self_repo)
              tag: v${newVersion}
              releaseNotesSource: 'inline'
              releaseNotesInline: "$(major).$(minor).$(revision)"
              tagSource: 'gitTag'
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'
